### ISSUE TITLE
Feature - Version Number

### ISSUE THREAD

**Issue by 2ndtlmining** [rosen-bridge/watcher#2]
Hey Team

Thanks again for the hard work with Rosen. Sure plenty of priorities to resolve. But was wondering if at all possible to add the version number in the Web UI making it easier to see if you are up to date or not.

**Suggestion**

<img width="198" alt="image" src="https://github.com/rosen-bridge/watcher/assets/108513481/a3227f76-3302-464f-add6-e09e4fd46e86">

**Comment by zargarzadehm** [comment]
This feature was added on 2.0.0.

**Comment by 2ndtlmining** [comment]
Super thanks mate!

<img width="47" alt="image" src="https://github.com/rosen-bridge/watcher/assets/108513481/46d9a515-9dc9-4b3c-aa96-bb907ce6caa6">
