### ISSUE TITLE
Bug - Dates are reversed in the revenue graph on homepage of UI

### ISSUE THREAD

**Issue by codefly** [rosen-bridge/watcher#3]
Currently running a Cardano watcher.

The revenue graph on the home page has the dates on the x axis reversed. See screenshot below:

![image](https://github.com/rosen-bridge/watcher/assets/1236869/e85e422c-8b4b-49c6-a08f-8ec0c8305391)

**Comment by zargarzadehm** [comment]
Should be fixed now
