### ISSUE TITLE
Migration from 1.1.2 to 2.0

### ISSUE THREAD

**Issue by adavault-ops** [rosen-bridge/watcher#4]
Inadvertently upgraded to 2.0.0 by running the usual docker commands then realised there was a major change that required additional steps. Followed instructions to downgrade back to 1.1.2. However 4 permits are still unavailable (6/10 available) and so this prevents unlocking to migrate to 2.0.0.

**Comment by zargarzadehm** [comment]
Please submit your issue to our Discord troubleshooting channel https://discord.gg/AHgsxhDKrQ.
